### ISSUE TITLE
Is there a way to add new users to an existing conversation channel?

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#23]
Hello Team, I'm trying to add users to the existing conversation channel I've created. I'm using this API endpoint to do so: /api/v3/channels/:channelId/users

I received the error as below:
![image](https://user-images.githubusercontent.com/74768384/105034140-acbdb580-5a8b-11eb-9f5c-3c860d3ce79b.png)

Is there a way I can add the user? Is there an endpoint I'm not aware of?

**Comment by stevenwangamity** [comment]
Hi @tpark-amity , it's not allowed to add users to conversation type channels, you need to specify the user ids in the channel creation

**Comment by tpark-amity** [comment]
> Hi @tpark-amity , it's not allowed to add users to conversation type channels, you need to specify the user ids in the channel creation

Will there be changes in the future to be able to add users into that channel?

**Comment by stevenwangamity** [comment]
@tpark-amity as a convention of how to handle conversation type, we don't have a plan to support that (Slack also doesn't support). Because chat history in a conversation type channel should only visible to the users who initially included in the conversation, one sample is that if you and I are having a 1:1 chat, we for sure don't want to drag another person in our group and allow him to see all the chat history.
